fix(TDKN-349): Fix Release Notes build (backport) (#995)
**What is the problem this Pull Request is trying to solve?**
Release is broken because of following error during Release Notes build:
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: RestClientException{statusCode=Optional.of(400), errorCollections=[ErrorCollection{status=400, errors={}, errorMessages=[An issue with key 'TPGOV-2168' does not exist for field 'id'.]}]}
16:35:07 [Thread-6] [INFO]     at org.talend.daikon.finders.git.JiraGitItemFinder.find (JiraGitItemFinder.java:97)
16:35:07 [Thread-6] [INFO]     at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
16:35:07 [Thread-6] [INFO]     at java.util.Spliterators$ArraySpliterator.forEachRemaining (Spliterators.java:948)
16:35:07 [Thread-6] [INFO]     at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:482)
16:35:07 [Thread-6] [INFO]     at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:472)
16:35:07 [Thread-6] [INFO]     at java.util.stream.ReduceOps$ReduceOp.evaluateSequential (ReduceOps.java:708)
16:35:07 [Thread-6] [INFO]     at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
16:35:07 [Thread-6] [INFO]     at java.util.stream.ReferencePipeline.reduce (ReferencePipeline.java:546)
16:35:07 [Thread-6] [INFO]     at org.talend.daikon.ReleaseNotes.execute (ReleaseNotes.java:91)
```
 
**What is the chosen solution to this problem?**
Handle 4XX error responses during calls to JIRA.
 
**Link to the JIRA issue**
https://jira.talendforge.org/browse/TDKN-349
 
**Please check if the Pull Request fulfills these requirements**
- [ ] The PR commit message follows our
[guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features,
coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are
all linked or available in the Pull Request

<!-- You can add more checkboxes here -->
 
**[ ] This Pull Request introduces a breaking change**
 
<!-- **Original Template** -->
<!--
https://github.com/Talend/tools/blob/master/tools-root-github/.github/PULL_REQUEST_TEMPLATE.md
-->